include: 
  # Start Ollama
  - ollama-runtime/ollama.yaml
  # Download LLMs
  - models/tinydolphin-llm.yaml
  #- models/phi-llm.yaml
  #- models/orca-mini-7b-llm.yaml

  # Start GenAI application demo
  - python-demo/app.yaml

  # Start the Python dev environment
  - python-dev-environment/app.yaml
