include: 
  # Start Ollama
  - ollama-runtime/ollama.yaml
  # Download LLMs
  - models/tinydolphin-llm.yaml
  - models/tinyllama-llm.yaml
  - models/deepseek-coder.yaml
  - models/gemma.yaml

  # Start GenAI application demo
  - python-demo/app.yaml

  # Start the Python dev environment
  - python-dev-environment/app.yaml
  # Start the JavaScript dev environment
  - js-dev-environment/app.yaml
