services:
  download-all-minilm-llm:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama-service:11434/api/pull", "-d", '{"name": "all-minilm"}']
    depends_on:
      ollama-service:
        condition: service_started

